// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_peak_acc_rate
NumericVector compute_peak_acc_rate(NumericVector acc, NumericVector start_idx, NumericVector peaks_idx, double samp_freq);
RcppExport SEXP _impactr_compute_peak_acc_rate(SEXP accSEXP, SEXP start_idxSEXP, SEXP peaks_idxSEXP, SEXP samp_freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type acc(accSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type start_idx(start_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type peaks_idx(peaks_idxSEXP);
    Rcpp::traits::input_parameter< double >::type samp_freq(samp_freqSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_peak_acc_rate(acc, start_idx, peaks_idx, samp_freq));
    return rcpp_result_gen;
END_RCPP
}
// compute_loading
NumericVector compute_loading(List coeff, NumericVector peaks, double body_mass);
RcppExport SEXP _impactr_compute_loading(SEXP coeffSEXP, SEXP peaksSEXP, SEXP body_massSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type coeff(coeffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< double >::type body_mass(body_massSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_loading(coeff, peaks, body_mass));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_impactr_compute_peak_acc_rate", (DL_FUNC) &_impactr_compute_peak_acc_rate, 4},
    {"_impactr_compute_loading", (DL_FUNC) &_impactr_compute_loading, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_impactr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
