// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_grf
NumericVector compute_grf(List coeff, NumericVector peaks, double body_mass);
RcppExport SEXP _impactr_compute_grf(SEXP coeffSEXP, SEXP peaksSEXP, SEXP body_massSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type coeff(coeffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< double >::type body_mass(body_massSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_grf(coeff, peaks, body_mass));
    return rcpp_result_gen;
END_RCPP
}
// compute_resultant
NumericVector compute_resultant(NumericVector acc_X, NumericVector acc_Y, NumericVector acc_Z);
RcppExport SEXP _impactr_compute_resultant(SEXP acc_XSEXP, SEXP acc_YSEXP, SEXP acc_ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type acc_X(acc_XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type acc_Y(acc_YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type acc_Z(acc_ZSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_resultant(acc_X, acc_Y, acc_Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_impactr_compute_grf", (DL_FUNC) &_impactr_compute_grf, 3},
    {"_impactr_compute_resultant", (DL_FUNC) &_impactr_compute_resultant, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_impactr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
