# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
get_curve_start <- function(acc, peaks_idx) {
    .Call(`_impactr_get_curve_start`, acc, peaks_idx)
}

#' @keywords internal
compute_peak_acc_rate <- function(acc, start_idx, peaks_idx, samp_freq) {
    .Call(`_impactr_compute_peak_acc_rate`, acc, start_idx, peaks_idx, samp_freq)
}

#' @keywords internal
compute_loading <- function(coeff, peaks, body_mass) {
    .Call(`_impactr_compute_loading`, coeff, peaks, body_mass)
}

#' @keywords internal
compute_resultant <- function(acc_X, acc_Y, acc_Z) {
    .Call(`_impactr_compute_resultant`, acc_X, acc_Y, acc_Z)
}

